"""Generate ``src/proofpack/narrate/tr39_confusables.py`` from Unicode's ``confusables.txt``.

DEC-60 (Josh, 23 September 2026): the ``free_text`` homoglyph rule reads the Unicode
Technical Standard #39 confusables data, vendored in the engine and never fetched at run
time. The full file is not committed; this script reads a local copy (fetched once, with
Josh's approval, by the orchestrator on 23 September 2026) and writes the subset the
checker reads: every entry whose target, with its combining marks (Unicode category
``Mn``) removed, is one or more ASCII letters. The target is written as the file gives it,
marks included; the checker's normaliser drops the marks.

Usage::

    python scripts/tr39_subset.py PATH/TO/confusables.txt            # writes the module
    python scripts/tr39_subset.py PATH/TO/confusables.txt --check    # exit 1 if it differs

``tests/test_e8_repair4.py`` imports :func:`parse` and :func:`subset` and compares the
result with the vendored module when the full file is present at
``PROOFPACK_TR39_FULL`` or at ``../workflows/data/confusables-18.0.0.txt``.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
import unicodedata
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TARGET = REPO / "src" / "proofpack" / "narrate" / "tr39_confusables.py"
SOURCE_URL = "https://www.unicode.org/Public/security/latest/confusables.txt"


def parse(data: bytes) -> tuple[dict[str, str], list[tuple[str, str]]]:
    """``(header, entries)``: the ``Version`` / ``Date`` header lines, the lines naming
    the copyright and terms of use, and every ``source ; target ; type`` entry as a
    ``(source, target)`` pair of strings."""
    text = data.decode("utf-8-sig")
    header: dict[str, str] = {"notice": ""}
    notice: list[str] = []
    entries: list[tuple[str, str]] = []
    for line in text.splitlines():
        if line.startswith("#"):
            body = line[1:].strip()
            m = re.match(r"(Version|Date): (.*)$", body)
            if m:
                header[m[1].lower()] = m[2].strip()
            elif body.startswith("©") or "trademark" in body or "terms of use" in body:
                notice.append(body)
            continue
        fields = line.split("#", 1)[0].split(";")
        if len(fields) < 3:
            continue
        source = "".join(chr(int(h, 16)) for h in fields[0].split())
        target = "".join(chr(int(h, 16)) for h in fields[1].split())
        entries.append((source, target))
    header["notice"] = "\n".join(notice)
    return header, entries


def _letters(target: str) -> str:
    return "".join(c for c in target if unicodedata.category(c) != "Mn")


def subset(entries: list[tuple[str, str]]) -> dict[int, str]:
    """The entries whose target, marks removed, is one or more ASCII letters, keyed by
    the source's code point (every source in 18.0.0 is one character)."""
    out: dict[int, str] = {}
    for source, target in entries:
        letters = _letters(target)
        if len(source) == 1 and letters and re.fullmatch(r"[A-Za-z]+", letters):
            out[ord(source)] = target
    return out


def _escape(c: str) -> str:
    if " " <= c <= "~" and c not in '"\\':
        return c
    if c == "\n":
        return "\\n"
    return f"\\u{ord(c):04x}" if ord(c) <= 0xFFFF else f"\\U{ord(c):08x}"


def _literal(s: str) -> str:
    """``s`` as an ASCII-only Python string literal."""
    return '"' + "".join(_escape(c) for c in s) + '"'


def _chunks(text: str, width: int = 80) -> list[str]:
    """``text`` as indented string literals of at most ``width`` characters each, the
    newlines kept, for an implicitly concatenated constant."""
    out: list[str] = []
    for i, line in enumerate(text.splitlines()):
        piece = line if i == len(text.splitlines()) - 1 else line + "\n"
        while piece:
            cut = len(piece) if len(piece) <= width else piece.rfind(" ", 0, width) + 1
            out.append(f"    {_literal(piece[:cut])}")
            piece = piece[cut:]
    return out


def render(header: dict[str, str], entries: list[tuple[str, str]], data: bytes) -> str:
    sub = subset(entries)
    lines = [
        '"""Unicode TR39 confusables: the subset the ``free_text`` rule reads (DEC-60).',
        "",
        "Generated by ``scripts/tr39_subset.py``; do not edit by hand. Source:",
        "",
        f"    {SOURCE_URL}",
        f"    Version: {header['version']}",
        f"    Date: {header['date']}",
        f"    SHA-256 of the full file: {hashlib.sha256(data).hexdigest()}",
        f"    Full file: {len(data):,} bytes, {len(entries):,} entries",
        "",
        f"The subset is the {len(sub):,} entries whose target, with its combining marks",
        "(category Mn) removed, is one or more ASCII letters; each target is written as the",
        "file gives it. Keys are source code points.",
        "",
        "The file's own copyright and terms-of-use lines are :data:`NOTICE`, as the file's",
        "header gives them (the terms: https://www.unicode.org/terms_of_use.html).",
        '"""',
        "",
        "NOTICE = (",
        *_chunks(header["notice"]),
        ")",
        f"SOURCE_URL = {_literal(SOURCE_URL)}",
        f"VERSION = {_literal(header['version'])}",
        f"DATE = {_literal(header['date'])}",
        f'FULL_SHA256 = "{hashlib.sha256(data).hexdigest()}"',
        f"FULL_BYTES = {len(data)}",
        f"FULL_ENTRIES = {len(entries)}",
        "",
        "CONFUSABLES: dict[int, str] = {",
    ]
    lines += [f"    0x{k:04X}: {_literal(v)}," for k, v in sorted(sub.items())]
    lines += ["}", ""]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("full_file")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    data = Path(args.full_file).read_bytes()
    header, entries = parse(data)
    text = render(header, entries, data)
    if args.check:
        current = TARGET.read_text(encoding="utf-8").replace("\r\n", "\n")
        same = current == text
        print("vendored subset matches" if same else "vendored subset DIFFERS")
        return 0 if same else 1
    TARGET.write_bytes(text.encode("utf-8"))
    print(f"wrote {TARGET} ({len(subset(entries))} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
