"""Scope and disclaimer strings, verbatim from D4 section 7 (design draft).

These are ProofPack's own words, pending review by the design partner's RA lead.
Templates never hard-code section numbers; guidance references are resolved via
``design/guidance_map_v1.csv``.
"""

SHORT_FORM = (
    "Statistical output generated by ProofPack v{version} on {date} from customer-supplied "
    "data and customer-declared criteria (author/date in Run Manifest). ProofPack does not "
    "verify data provenance, labelling accuracy, reference-standard validity, sampling or "
    "study design, and does not select acceptance criteria, thresholds or margins. Narrative "
    "sections are machine-drafted and must be reviewed by the manufacturer's qualified "
    "statistician and regulatory lead before use. Guidance references: {guidance_refs}. "
    "This output is not a regulatory opinion; no regulator has endorsed this tool."
)

LONG_FORM_TITLE = "Scope and limits of this document"

LONG_FORM_ITEMS: tuple[tuple[str, str], ...] = (
    (
        "What ProofPack is.",
        "ProofPack is statistical software that computes performance estimates, confidence "
        "intervals, differences and distribution comparisons from a customer-supplied test table "
        "and renders them into document templates. It is not a certification, an audit, a "
        "regulatory opinion, a clinical evaluation or a submission. No regulator has reviewed, "
        "accepted, approved or endorsed this tool or its outputs.",
    ),
    (
        "What is warranted.",
        "Global Phoenix Solutions Ltd warrants the computational correctness of the numbers in "
        "this document to the tolerances stated in the Methods Appendix (T7), on the reference "
        "platform stated in the Run Manifest (T8). Nothing else is warranted.",
    ),
    (
        "What is the manufacturer's responsibility.",
        "The manufacturer selected and is responsible for: the data and its provenance; the "
        "labels and the reference standard or comparator and their validity; the positive class, "
        "score orientation, thresholds and their provenance; the intended-use prevalence; the "
        "acceptance criteria, non-inferiority margins, subgroup bounds and fairness criterion of "
        "interest (each recorded with author, date and justification in T8); the "
        'pre-specification of subgroups; and all text in sections marked "Manufacturer text".',
    ),
    (
        "Out of scope (never performed by ProofPack).",
        "Study design; sample-size calculation; selection of acceptance criteria, margins or "
        "thresholds; adjudication and reference-standard construction (rater columns are never "
        "used to construct labels); MRMC or reader studies; clinical-outcome or trial evidence; "
        "literature review; valid clinical association; benefit-risk conclusions; risk "
        "management; cybersecurity documentation; human factors; explainability; complaints, "
        "vigilance and incident trend reporting (MDR Art. 88; GB SI 2024/1368 reg. 44ZN); "
        "authorship of the 510(k) Summary (21 CFR 807.92).",
    ),
    (
        "Guidance status.",
        "Every guidance reference in this document names the document, its version or date and "
        "whether it is draft or final. Where the reference is to the FDA draft guidance "
        '"Artificial Intelligence-Enabled Device Software Functions: Lifecycle Management and '
        'Marketing Submission Recommendations" (January 2025), it is a draft, not for '
        "implementation, and section numbering may change on finalisation. References to the "
        "FDA PCCP guidance are to the version issued 4 December 2024 and updated 18 August 2025. "
        'References to the FDA "Statistical Guidance on Reporting Results from Studies '
        'Evaluating Diagnostic Tests" are to the final guidance of 13 March 2007.',
    ),
    (
        "Narrative.",
        "All prose is machine-drafted from a fixed sentence library bound to computed "
        "quantities. It must be reviewed by the manufacturer's qualified statistician and "
        "regulatory lead before use. Every number in the prose is traceable to a JSON path in "
        "the accompanying pack.json.",
    ),
    (
        "Conventions that are ProofPack's, not a regulator's.",
        "Low-n tier labels, the 200/200 calibration-curve convention, the choice of Wilson (no "
        "continuity correction) with Clopper-Pearson alongside at k = 0 or k = n, and bootstrap "
        "settings are ProofPack conventions, stated in T7 with citations. No regulator "
        "specifies per-stratum minimum sizes.",
    ),
    (
        "Synthetic or demonstration data.",
        'Where this document is marked "SYNTHETIC - illustrative", "DEMO" or "TRIAL", it '
        "contains no real evidence and must not be used in any regulatory record.",
    ),
)

#: Marker strings used on packs produced from non-evidence data.
SYNTHETIC_MARK = "SYNTHETIC - illustrative"
DEMO_MARK = "DEMO"
TRIAL_MARK = "TRIAL"
